### ISSUE TITLE
Use dropdown box for filter by user

### ISSUE THREAD

**Issue by raskas** [kalmanolah/925r#10]
User list is too large (and not correctly sorted) to show as list

http://stackoverflow.com/questions/5429276/how-to-change-the-django-admin-filter-to-use-a-dropdown-instead-of-list

**Comment by kalmanolah** [comment]
Implemented in https://github.com/kalmanolah/925r/commit/63fb56ca60f1fffb72505e4ec46f80b4beecefe6
