### ISSUE TITLE
Add search/filtering functionality to admin interfaces

### ISSUE THREAD

**Issue by JanLaureys** [kalmanolah/925r#3]
For example: The leaves page has like 1000's of entries and it's at the moment pretty impossible to search by user for instance.

**Comment by kalmanolah** [comment]
I've added some pretty neat filtering for leaves in commit https://github.com/kalmanolah/925r/commit/08fb203262fdc1526d15b189421a3a7e43bf3935 . Stuff like a search box which searches users, leave types, dates, leave status, etc.. as well as sidebar filters for all of that stuff.
